import Head from 'next/head'
import Image from 'next/image'
import { Header } from '../components/header/Header'
import { Nav } from '../components/header/Nav'
import { Results } from '../components/results/Results'
import requests from '../utils/requests'

export default function Home({ results, linkConsulta }) {


  return (
    <div >
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />
      {/* Nav */}

      <Nav />
      {/* Results */}

      <Results results={results}/>

    </div>
  )
}


export async function getServerSideProps(context) {

  const genre = context.query.genre;
  const link = `https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`

  console.log('link', link)
  const request = await fetch(link).then(res => res.json())

  return {
    props: {
      results: request.results ? request.results : null,
      linkConsulta : link
    }
  }
}
